<?php
/**
 * @return mixed
 */
function li_get_authors()
{
    global $wpdb;

    $query = "
        SELECT u.ID, u.user_login
        FROM {$wpdb->users} AS u
        WHERE 1=1
        ORDER BY u.user_login ASC
    ";
    $results = $wpdb->get_results($query, OBJECT);

    return $results;
}

/**
 * @return array
 */
function li_get_post_statuses()
{
    $array = array('publish', 'future', 'draft', 'pending', 'private', 'trash', 'auto-draft', 'inherit');

    return $array;
}

/**
 * @return array
 */
function li_get_post_types()
{
    $return = array();

    // Get WordPress post types
    $args = array(
        'public' => true,
        //'_builtin' => true
    );
    $post_types = get_post_types($args, 'names', 'and');

    // Remove Attachments
    unset( $post_types['attachment'] );

    // Return only simple value
    if( count($post_types) ) foreach( $post_types as $post_type ) $return[] = $post_type;

    return $return;
}

/**
 * @param string $key
 * @return string
 * @example: https://baconipsum.com/api/?type=all-meat-filler&paras=5
 */
function li_get_rand_content( $key = 'post_title' )
{
    // Array of Lorem ipsum
    $array = array(
        array(
            'post_title' => 'Nunc hendrerit volutpat neque, nec iaculis metus ornare non...',
            'post_excerpt' => 'Ex sed mauris, sed placerat elit lacus sed nisi. Morbi at leo tortor. Phasellus rhoncus orci a mi convallis, non ultricies ante egestas.',
            'post_content' => 'Sed feugiat ex nec mattis elementum. Vestibulum mollis nisi vel arcu suscipit mollis. Donec facilisis risus vel suscipit pretium. Nam feugiat, magna nec vulputate convallis, leo enim placerat mauris, sed placerat elit lacus sed nisi. Morbi at leo tortor. Phasellus rhoncus orci a mi convallis, non ultricies ante egestas. Donec vulputate dui nulla, sed aliquam libero porta nec. Nunc hendrerit volutpat neque, nec iaculis metus ornare non. Aenean a mauris vel dolor fringilla commodo. Mauris accumsan hendrerit nulla quis varius.'
        ),
        array(
            'post_title' => 'Integer malesuada odio ac magna suscipit accumsan',
            'post_excerpt' => 'Aliquam vel mi euismod, convallis leo at, ultrices enim. Sed sit amet mi leo. Maecenas vel ornare risus. Ut maximus laoreet elit sit amet fermentum. Sed ut euismod diam. Aenean finibus eu libero et interdum.',
            'post_content' => 'In egestas ex sed elit dapibus aliquet. Nunc tortor ante, cursus ut imperdiet a, laoreet et libero. Donec vitae nibh ullamcorper, faucibus lacus sit amet, ullamcorper metus. Aliquam vel mi euismod, convallis leo at, ultrices enim. Sed sit amet mi leo. Maecenas vel ornare risus. Ut maximus laoreet elit sit amet fermentum. Sed ut euismod diam. Aenean finibus eu libero et interdum. Integer malesuada odio ac magna suscipit accumsan. Nullam diam lectus, mollis et libero eu, porta laoreet sem. Praesent accumsan lectus orci, non luctus neque cursus et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
        ),
        array(
            'post_title' => 'Sed ac lorem sed tortor sollicitudin porta suspendisse pretium',
            'post_excerpt' => 'Sed convallis orci. Mauris congue fringilla odio iaculis iaculis. Phasellus a felis leo. Nam magna nisi, mollis a tempus a, vehicula quis ante. Donec vel cursus mauris. Nunc viverra orci sit amet sagittis egestas.',
            'post_content' => 'Suspendisse velit sapien, aliquam vitae libero a, ornare porttitor nulla. Fusce malesuada neque id libero sagittis, maximus porttitor odio lacinia. Sed quis malesuada tortor. Sed ac lorem sed tortor sollicitudin porta. Suspendisse pretium dapibus augue, nec dignissim lacus scelerisque non. Aenean tincidunt dolor est, aliquam tempus quam volutpat ac. Fusce ac rhoncus velit, sed convallis orci. Mauris congue fringilla odio iaculis iaculis. Phasellus a felis leo. Nam magna nisi, mollis a tempus a, vehicula quis ante. Donec vel cursus mauris. Nunc viverra orci sit amet sagittis egestas. Sed tincidunt, sem sit amet consectetur tincidunt, tellus dui rhoncus nulla, a vestibulum est elit sit amet ex. Cras aliquam leo magna, at facilisis orci bibendum sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tempus tortor nec libero porttitor placerat.'
        ),
        array(
            'post_title' => 'Sed vitae magna neque aenean fermentum erat orci, ut blandit risus',
            'post_excerpt' => 'Ed fermentum quis lectus sit amet ornare. Mauris finibus cursus odio a fringilla. Etiam facilisis risus a augue tincidunt egestas. Sed vitae magna neque. Aenean fermentum erat orci, ut blandit risus pharetra non.',
            'post_content' => 'Etiam lacus nisl, rutrum at ligula ut, facilisis malesuada nisi. Sed fermentum quis lectus sit amet ornare. Mauris finibus cursus odio a fringilla. Etiam facilisis risus a augue tincidunt egestas. Sed vitae magna neque. Aenean fermentum erat orci, ut blandit risus pharetra non. Curabitur sagittis, lectus sit amet accumsan porttitor, odio ex porttitor neque, ut cursus urna ipsum sit amet quam. Pellentesque eget iaculis nisl. Nullam congue, elit at tempus dapibus, lorem ipsum tristique mauris, tristique sodales magna metus nec diam. Phasellus ac convallis augue. Donec sit amet ullamcorper diam. Morbi lobortis consequat lectus, non elementum purus blandit at. Aenean vestibulum vel urna eget posuere.'
        ),
        array(
            'post_title' => 'Prese una cassetta di caratteri e li assemblò per preparare un testo campione',
            'post_excerpt' => 'Pervenendoci sostanzialmente inalterato. Fu reso popolare, negli anni ’60, con la diffusione dei fogli di caratteri trasferibili “Letraset”, che contenevano passaggi del Lorem Ipsum, e più recentemente da software di impaginazione come Aldus PageMaker.',
            'post_content' => 'Lorem Ipsum è un testo segnaposto utilizzato nel settore della tipografia e della stampa. Lorem Ipsum è considerato il testo segnaposto standard sin dal sedicesimo secolo, quando un anonimo tipografo prese una cassetta di caratteri e li assemblò per preparare un testo campione. È sopravvissuto non solo a più di cinque secoli, ma anche al passaggio alla videoimpaginazione, pervenendoci sostanzialmente inalterato. Fu reso popolare, negli anni ’60, con la diffusione dei fogli di caratteri trasferibili “Letraset”, che contenevano passaggi del Lorem Ipsum, e più recentemente da software di impaginazione come Aldus PageMaker, che includeva versioni del Lorem Ipsum.'
        ),
        array(
            'post_title' => 'Le gambe, numerose e sottili da far pietà, rispetto alla sua corporatura normale',
            'post_excerpt' => 'La sua camera, una stanzetta di giuste proporzioni, soltanto un po’ piccola, se ne stava tranquilla fra le quattro ben note pareti. Sulla tavola, un campionario disfatto di tessuti - Samsa era commesso viaggiatore e sopra.',
            'post_content' => 'Gregorio Samsa, svegliandosi una mattina da sogni agitati, si trovò trasformato, nel suo letto, in un enorme insetto immondo. Riposava sulla schiena, dura come una corazza, e sollevando un poco il capo vedeva il suo ventre arcuato, bruno e diviso in tanti segmenti ricurvi, in cima a cui la coperta da letto, vicina a scivolar giù tutta, si manteneva a fatica. Le gambe, numerose e sottili da far pietà, rispetto alla sua corporatura normale, tremolavano senza tregua in un confuso luccichio dinanzi ai suoi occhi. Cosa m’è avvenuto? pensò. Non era un sogno. La sua camera, una stanzetta di giuste proporzioni, soltanto un po’ piccola, se ne stava tranquilla fra le quattro ben note pareti. Sulla tavola, un campionario disfatto di tessuti - Samsa era commesso viaggiatore e sopra, appeso alla parete, un ritratto, ritagliato da lui - non era molto - da una rivista illustrata e messo dentro una bella cornice dorata: raffigurava una donna seduta, ma ben dritta sul busto, con un berretto e un boa di pelliccia; essa levava incontro a chi guardava un pesante manicotto, in cui scompariva tutto l’avambraccio.'
        ),
        array(
            'post_title' => 'Un piccolo ruscello chiamato Devoto Oli attraversa quei luoghi, rifornendoli di tutte!',
            'post_excerpt' => 'Un piccolo ruscello chiamato Devoto Oli attraversa quei luoghi, rifornendoli di tutte le regolalie di cui hanno bisogno. È una terra paradismatica, un paese della cuccagna in cui golose porzioni di proposizioni arrostite volano in bocca a chi le desideri.',
            'post_content' => 'In una terra lontana, dietro le montagne Parole, lontani dalle terre di Vocalia e Consonantia, vivono i testi casuali. Vivono isolati nella cittadina di Lettere, sulle coste del Semantico, un immenso oceano linguistico. Un piccolo ruscello chiamato Devoto Oli attraversa quei luoghi, rifornendoli di tutte le regolalie di cui hanno bisogno. È una terra paradismatica, un paese della cuccagna in cui golose porzioni di proposizioni arrostite volano in bocca a chi le desideri. Non una volta i testi casuali sono stati dominati dall’onnipotente Interpunzione, una vita davvero non ortografica. Un giorno però accadde che la piccola riga di un testo casuale, di nome Lorem ipsum, decise di andare a esplorare la vasta Grammatica. Il grande Oximox tentò di dissuaderla, poiché quel luogo pullulava di virgole spietate, punti interrogativi selvaggi e subdoli punti e virgola, ma il piccolo testo casuale non si fece certo fuorviare. Raccolse le sue sette maiuscole, fece scorrere la sua iniziale nella cintura, e si mise in cammino. Quando superò i primi colli dei monti Corsivi, si voltò a guardare un’ultima volta la skyline di Lettere, la sua città, la headline del villaggio Alfabeto e la subline della sua stessa strada, il vicolo Riga. Una domanda retorica.'
        ),
        array(
            'post_title' => 'Lingua franca va esser plu simplic e regulari quam',
            'post_excerpt' => 'It va esser tam simplic quam Occidental in fact, it va esser Occidental. A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental.',
            'post_content' => 'Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues. It va esser tam simplic quam Occidental in fact, it va esser Occidental. A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es.Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.'
        ),
        array(
            'post_title' => 'Leo ligula, porttitor eu, consequat vitae, eleifend ac, enim',
            'post_excerpt' => 'Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet.',
            'post_content' => 'Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc.'
        ),
        array(
            'post_title' => 'Rump strip steak sausage jowl landjaeger meatloaf',
            'post_excerpt' => 'Ham hock spare ribs burgdoggen, meatloaf doner pig shankle pork loin alcatra prosciutto capicola jerky leberkas.  Salami spare ribs shankle burgdoggen andouille kevin pig, meatloaf alcatra strip steak turkey sausage boudin.  Burgdoggen landjaeger ham hock pancetta.',
            'post_content' => 'Bacon ipsum dolor amet salami boudin chuck jerky, picanha alcatra corned beef meatball biltong ham hock prosciutto drumstick burgdoggen t-bone tongue.  T-bone landjaeger prosciutto meatloaf sausage chicken short ribs tenderloin pig shank alcatra chuck.  Doner tail tongue rump pork belly ribeye short ribs.  Tenderloin pork chop beef ribs, strip steak capicola landjaeger andouille.  Meatball pig boudin bresaola.  Turducken turkey capicola strip steak.","Boudin tongue prosciutto, short loin venison ribeye ham corned beef.  Chicken pork belly picanha, andouille meatball shankle beef ribs rump pork.  Tail spare ribs turducken pork loin swine, ground round porchetta boudin short ribs flank tri-tip.  Pork loin meatball drumstick bresaola swine t-bone chicken pancetta cupim venison.","Ham pork chop ribeye shankle pork.  Swine capicola picanha burgdoggen cupim, jerky meatball drumstick venison.  Venison shankle sirloin pancetta pork chop kielbasa.  Tri-tip corned beef andouille pancetta ball tip turducken spare ribs boudin short ribs leberkas pork belly.","Tri-tip rump beef jowl ham hock pastrami swine doner ribeye tenderloin shoulder venison chuck beef ribs.  Ball tip prosciutto meatball tenderloin burgdoggen filet mignon tail turducken turkey jowl ham hock.  Beef hamburger shankle bacon meatloaf cow porchetta.  Salami swine frankfurter tongue doner tenderloin pork chop pancetta bacon shank bresaola jowl shankle tail.'
        ),
        array(
            'post_title' => 'Capicola pork loin meatball, rump chicken alcatra chuck shankle ball tip drumstick cow',
            'post_excerpt' => 'Ribeye capicola chuck, t-bone cupim pork sirloin strip steak sausage pork belly cow short loin kevin.  Picanha porchetta ball tip meatball beef ribs boudin.  Venison shank pastrami pancetta.',
            'post_content' => 'Ham strip steak beef ribs, pork loin shankle bacon rump ball tip tri-tip meatball burgdoggen sausage kevin.  Boudin ham spare ribs andouille strip steak turkey.  Short ribs beef ribs capicola pork loin landjaeger flank pork belly pig cow venison chuck meatloaf tongue.  Meatloaf ribeye bresaola shankle turkey beef swine.  Short ribs sausage andouille shankle jerky alcatra ham hock beef ribs tri-tip kevin pork loin ball tip prosciutto chicken brisket.  Hamburger tenderloin landjaeger cupim sausage.  Pork chop turkey spare ribs, strip steak sirloin jerky beef ribs meatloaf t-bone picanha.","Ham hock fatback sirloin, tongue filet mignon swine rump.  Ribeye capicola chuck, t-bone cupim pork sirloin strip steak sausage pork belly cow short loin kevin.  Picanha porchetta ball tip meatball beef ribs boudin.  Venison shank pastrami pancetta.  Pork belly strip steak pork tongue sausage shank, tri-tip chicken corned beef landjaeger shankle turducken ground round ribeye cupim.  Flank brisket short loin chicken bacon pork belly strip steak rump pig, t-bone capicola cow swine drumstick.","Chuck swine capicola, andouille spare ribs bresaola ham leberkas landjaeger filet mignon pork belly pastrami fatback.  Jowl rump swine, doner pork loin short ribs meatloaf capicola venison.  Beef pastrami capicola ham prosciutto venison pork bacon, boudin spare ribs pork belly tenderloin pig.  Pork chop biltong tenderloin pork loin sausage pork belly shoulder kevin strip steak fatback.  Beef ribs burgdoggen short loin fatback beef ham, short ribs capicola pork loin andouille.  Capicola pork loin meatball, rump chicken alcatra chuck shankle ball tip drumstick cow.  Pork loin fatback chicken, cow shankle kielbasa kevin burgdoggen turkey porchetta ham beef.","Pastrami pork pork loin tri-tip, salami jowl ham kielbasa filet mignon.  Meatball ball tip jerky, capicola swine tongue chicken andouille.  Short ribs ribeye chuck spare ribs, bacon ground round turkey shoulder.  Drumstick tail meatball pork belly bresaola pancetta cow capicola fatback beef kevin biltong beef ribs.  Meatball pork loin boudin venison.  Doner tail jerky pork loin swine sausage short ribs.","Chuck ham flank kevin.  Ground round shankle doner beef jerky chicken frankfurter tongue pastrami pork loin ham hock.  Alcatra andouille tri-tip frankfurter landjaeger fatback.  Short loin burgdoggen picanha, drumstick turkey beef ribs ball tip shoulder alcatra chuck short ribs fatback cow pork belly corned beef.'
        ),
        array(
            'post_title' => 'T-bone flank pancetta salami filet mignon, drumstick pork chop tongue tri-tip',
            'post_excerpt' => 'Shank biltong jerky, meatball cupim chuck porchetta shankle pork kevin.  Pork pork belly jerky ribeye burgdoggen meatloaf corned beef.  Bresaola rump turducken pig cupim.  Leberkas filet mignon beef, strip steak turkey prosciutto biltong frankfurter bresaola.  Corned beef swine tail jowl burgdoggen ham hock rump.',
            'post_content' => 'Jerky swine sirloin meatball, shank cupim fatback rump frankfurter beef ribs.  Flank kielbasa frankfurter tenderloin.  Sausage pork salami shankle flank picanha.  Sirloin chuck pastrami spare ribs.  Alcatra chuck kielbasa ham andouille tenderloin swine ball tip sirloin.  Bresaola rump cupim flank ground round, short loin pig kevin.","Tri-tip cupim venison pork loin, jowl doner sirloin pork boudin cow beef frankfurter drumstick ham.  Capicola ground round t-bone swine pork corned beef shankle spare ribs.  Corned beef tri-tip short loin pancetta cupim bresaola porchetta, chuck ball tip brisket turkey.  Burgdoggen rump ham, frankfurter alcatra leberkas jowl.  Salami corned beef frankfurter, strip steak meatball ball tip doner pork belly ground round t-bone jowl hamburger ham hock shank brisket, spare ribs pig andouille.  Salami chicken meatloaf kevin meatball tongue leberkas spare ribs sausage brisket shankle swine ribeye.  Shank biltong jerky, meatball cupim chuck porchetta shankle pork kevin.  Pork pork belly jerky ribeye burgdoggen meatloaf corned beef.  Bresaola rump turducken pig cupim.  Leberkas filet mignon beef, strip steak turkey prosciutto biltong frankfurter bresaola.  Corned beef swine tail jowl burgdoggen ham hock rump.'
        ),
        array(
            'post_title' => 'Porchetta capicola pork belly ribeye corned beef tail',
            'post_excerpt' => 'Pork belly ribeye corned beef tail. Ball tip meatloaf pork chop brisket, capicola swine rump ham hock kevin leberkas ground round hamburger.  Meatloaf biltong hamburger pancetta.  Tail jowl leberkas salami bresaola filet mignon shoulder rump beef ribs porchetta sirloin picanha kielbasa spare ribs pork.',
            'post_content' => 'Venison ribeye short ribs meatball prosciutto shank swine bresaola porchetta.  Beef picanha burgdoggen pig shank ribeye, drumstick t-bone prosciutto chicken short loin corned beef filet mignon shankle kevin.  Short ribs pork belly short loin ham salami, burgdoggen brisket chicken.  Biltong brisket landjaeger prosciutto chuck.","Jowl biltong picanha ham hock.  Spare ribs landjaeger biltong tail, tongue pancetta alcatra andouille rump tenderloin pork loin beef ribs pig bresaola fatback.  Tri-tip ball tip capicola brisket turkey.  Rump beef filet mignon pastrami pancetta venison.","Boudin pork meatball capicola flank pork loin, ham hock frankfurter andouille brisket ribeye.  Frankfurter hamburger doner, leberkas beef ribs chicken rump boudin flank filet mignon.  Corned beef tongue ball tip pig cow ham burgdoggen short ribs picanha.  Pork belly ham short loin, leberkas meatball hamburger jerky ham hock turducken drumstick picanha tenderloin.  Pig ground ham hock landjaeger pancetta beef ribs doner chicken tongue spare ribs tri-tip.","Ball tip pork kielbasa t-bone tail rump.  Fatback burgdoggen pork chop salami chicken rump boudin andouille.  Brisket kevin alcatra ball tip swine hamburger.  Landjaeger tail ball tip cow kielbasa shank burgdoggen.  Porchetta filet mignon tongue flank ground round ribeye prosciutto, chicken biltong capicola corned beef sirloin hamburger turducken.'
        ),
        array(
            'post_title' => 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
            'post_excerpt' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.',
            'post_content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
        ),
        array(
            'post_title' => 'Shoulder shankle bresaola, porchetta pork chop spare ribs swine beef ribs cow tongue ground round shank',
            'post_excerpt' => 'Spare ribs pork loin beef ribs shank salami sausage pork leberkas, picanha ham hock jowl chicken capicola tongue short loin. Shoulder shankle bresaola, porchetta pork chop spare ribs swine beef ribs cow tongue ground round shank.  Ribeye fatback prosciutto ham hock.',
            'post_content' => 'Beef ribs bresaola kevin, flank kielbasa meatloaf pork.  Shank pork loin corned beef t-bone, meatball short ribs burgdoggen jowl rump pork ground round biltong frankfurter.  Kevin ground round drumstick corned beef, alcatra tri-tip pancetta tongue chuck venison burgdoggen pork loin pork chop leberkas.  Sirloin alcatra cow pork chop beef ball tip strip steak brisket.  Doner shoulder beef biltong alcatra boudin. Turducken cow pork belly kevin pork chop salami venison pastrami meatball ribeye.  Capicola chuck jowl alcatra, doner flank picanha frankfurter pig burgdoggen.","Ball tip jerky pork tenderloin.  Venison kielbasa t-bone rump, kevin biltong ham shoulder brisket spare ribs.  Biltong bresaola meatball alcatra.  Short loin pork chop ham hock, flank shoulder bresaola beef ribs ribeye meatball porchetta filet mignon landjaeger salami fatback.  Shank frankfurter rump short loin burgdoggen ham.","Shoulder tenderloin biltong pastrami..'
        ),
        array(
            'post_title' => 'Ribeye jowl leberkas, pancetta swine turkey',
            'post_excerpt' => 'Meatball tongue chuck, leberkas meatloaf picanha capicola.  Shank rump sirloin cupim ham hock porchetta pork chop ham cow biltong. Kevin turducken spare ribs boudin picanha biltong t-bone prosciutto turkey.',
            'post_content' => 'Meatball tri-tip shank picanha tenderloin spare ribs, jowl ribeye.  Short ribs drumstick burgdoggen turducken beef leberkas bresaola rump biltong turkey doner alcatra prosciutto sausage porchetta.  Filet mignon short loin ribeye cupim swine cow chuck.  T-bone doner ham hock jerky ground round strip steak.  Beef drumstick burgdoggen bacon pancetta pork loin strip steak filet mignon ham kielbasa sausage tri-tip bresaola t-bone.  Drumstick landjaeger picanha turkey swine pancetta andouille.","Pancetta pig alcatra burgdoggen tenderloin, ball tip bresaola turducken ribeye fatback venison strip steak pork loin.  Alcatra ham hock cow strip steak hamburger pastrami sirloin jowl shoulder t-bone rump spare ribs.  Tenderloin beef ribs sirloin, doner andouille salami sausage shankle fatback.  Ground round t-bone bresaola fatback jerky, meatloaf pork filet mignon.  Meatball tongue chuck, leberkas meatloaf picanha capicola.  Shank rump sirloin cupim ham hock porchetta pork chop ham cow biltong.","Kevin turducken spare ribs boudin picanha biltong t-bone prosciutto turkey.  Ball tip tenderloin shank bacon pork chop t-bone fatback swine beef corned beef capicola shoulder jerky.  Ham hock kevin jowl, cow tenderloin sirloin beef ribeye tri-tip beef ribs turkey.  Turkey strip steak boudin, bresaola leberkas jerky sirloin cupim beef corned beef. Porchetta turkey pork loin boudin meatloaf cupim bacon, beef ribs filet mignon venison meatball hamburger.  Jowl pork chop tenderloin kevin prosciutto pork.'
        ),
        array(
            'post_title' => 'Kielbasa corned beef sausage, burgdoggen ham filet mignon porchetta doner',
            'post_excerpt' => 'Landjaeger jowl tenderloin shank pork belly kielbasa short ribs beef ham doner swine.","Turducken prosciutto ham hock kevin leberkas.  Porchetta shankle picanha landjaeger tongue sausage boudin leberkas beef ribs pig shank fatback ham hock cow.  Capicola picanha pork loin.',
            'post_content' => 'Venison pork ball tip bresaola, porchetta fatback jerky shank filet mignon spare ribs sirloin tenderloin rump boudin pancetta.  Alcatra rump capicola meatball.  T-bone porchetta chicken prosciutto turkey.  Salami tongue corned beef, tail prosciutto short loin flank capicola bresaola shank.  Landjaeger jowl tenderloin shank pork belly kielbasa short ribs beef ham doner swine. Bresaola strip steak swine pork chop pork belly chuck.  Chicken pastrami sirloin beef ribs doner short loin leberkas venison filet mignon jowl turducken meatball shank jerky.  Ham capicola porchetta biltong tenderloin short loin short ribs filet mignon rump cow chicken.","Cow prosciutto tongue brisket.  T-bone sausage alcatra sirloin tenderloin swine brisket prosciutto pork tri-tip meatball.  Kielbasa salami pork loin tail.  Pig rump alcatra biltong venison.  Doner tenderloin picanha short ribs flank alcatra hamburger pork chop frankfurter tail chuck ribeye burgdoggen rump.","Prosciutto meatloaf picanha porchetta boudin, bacon alcatra flank venison pork belly tail chuck pancetta leberkas shoulder.  Ground round shoulder bresaola pancetta.  Fatback tenderloin filet mignon pastrami pork biltong porchetta corned beef, tri-tip pork belly boudin shankle shank.  Beef ribs rump jerky hamburger.  Boudin turducken cow beef ribs capicola strip steak bresaola doner pork belly swine short ribs ground round jowl.  Venison bresaola t-bone ground round flank corned beef capicola turkey rump shoulder kielbasa.'
        ),
        array(
            'post_title' => 'Meatloaf strip steak frankfurter, porchetta',
            'post_excerpt' => 'Chicken prosciutto jerky, shoulder beef ham kevin landjaeger doner tail short ribs pork swine cow meatloaf.  Cow pig doner kielbasa spare ribs.',
            'post_content' => 'Alcatra ham sirloin, beef sausage tongue corned beef pastrami cow.  Cow prosciutto swine, burgdoggen ribeye flank landjaeger boudin beef ribs.  Ground round rump jerky shankle tenderloin spare ribs, tongue short loin pancetta chicken shankle filet mignon leberkas.  Picanha tenderloin beef, ribeye sausage andouille spare ribs cow short loin.  Ribeye capicola pastrami turducken venison.  Porchetta boudin tongue shankle brisket corned beef andouille cow short loin pancetta t-bone pork sausage.  Swine pork brisket, fatback short ribs frankfurter ribeye chuck.","Ground round jowl short ribs beef ribs.  Swine tail prosciutto beef ribs, capicola venison tenderloin beef drumstick tongue pork loin ribeye rump frankfurter.  Chuck tenderloin kevin, cow t-bone shankle ham ham hock turducken porchetta.  Tenderloin cupim shoulder, swine flank meatloaf chicken turducken ham.","Burgdoggen bresaola sausage landjaeger venison chuck pork cow pork loin picanha swine turducken chicken biltong.  Cupim ham hock ground round, pork loin jowl hamburger t-bone frankfurter pancetta landjaeger andouille beef tenderloin alcatra.  Tenderloin short ribs swine t-bone jerky strip steak.  Cow pancetta meatloaf burgdoggen.  Meatloaf strip steak frankfurter, porchetta short loin chicken tri-tip jowl meatball doner ham hock rump burgdoggen.  Tail andouille venison alcatra bacon, jowl pastrami sirloin strip steak shankle kevin shoulder spare ribs.  Burgdoggen beef ribs cow, andouille hamburger biltong fatback filet mignon pastrami sausage brisket pork loin cupim.'
        ),
        array(
            'post_title' => 'Tenderloin kielbasa filet mignon, meatball pig bresaola ribeye pork chop cupim cow brisket',
            'post_excerpt' => 'Andouille cupim sirloin tongue drumstick ribeye prosciutto turducken salami.  Salami beef meatball jowl, strip steak pig drumstick ham hock ribeye chicken alcatra. Burgdoggen alcatra salami sirloin swine t-bone beef capicola pork chop bacon pork loin ham kielbasa kevin.  Tri-tip pork loin venison brisket frankfurter.',
            'post_content' => 'Short ribs pancetta shankle andouille venison meatloaf rump tongue.  Pig shoulder salami biltong, landjaeger cupim hamburger boudin jerky.  Pork belly pork turducken jowl, salami pig hamburger turkey burgdoggen filet mignon kevin shoulder.  Chuck picanha ground round fatback, alcatra tail kevin pork turkey meatloaf ham hock pig drumstick jowl pork loin.  Chicken jowl pastrami, porchetta pig bresaola ball tip.  Tenderloin kielbasa filet mignon, meatball pig bresaola ribeye pork chop cupim cow brisket.  Picanha pork belly biltong turducken, sausage cupim chuck tongue pig rump pork chop prosciutto.","Kevin boudin cupim leberkas, beef ribs short loin venison fatback jerky filet mignon pork chop burgdoggen ribeye spare ribs.  Landjaeger cupim beef, tenderloin shankle fatback pork belly salami shank picanha meatball kielbasa turducken frankfurter.  Pastrami landjaeger tri-tip, andouille jowl fatback flank shank hamburger.  Chuck bacon sirloin sausage.  Cupim leberkas pork belly pig kevin.  Tail pork loin picanha, meatball kielbasa filet mignon rump beef chicken.","Short ribs andouille burgdoggen prosciutto doner shankle.  Doner tail short loin picanha meatball shoulder, beef shank bresaola turducken sirloin.  Ground round shank picanha sirloin beef pastrami porchetta cow ham hock corned beef, prosciutto hamburger.  Flank chuck prosciutto ground round, porchetta shoulder cupim beef ribs sausage drumstick kielbasa cow bresaola jerky.  Andouille cupim sirloin tongue drumstick ribeye prosciutto turducken salami.'
        ),
        array(
            'post_title' => 'Meatball brisket pork filet mignon pancetta!',
            'post_excerpt' => 'Biltong tri-tip hamburger, jowl drumstick prosciutto pork bacon t-bone leberkas strip steak ham hock.  Strip steak bacon tri-tip leberkas jowl.  Meatball brisket pork filet mignon pancetta.  Ball tip short loin shoulder pig pork belly ribeye rump salami brisket tri-tip prosciutto landjaeger.","Ham hock chuck cow kevin boudin.',
            'post_content' => 'Pork chop ground round spare ribs cupim ham hock shankle sirloin hamburger.  Capicola jerky brisket fatback.  Ground round shank porchetta tongue, tail beef ribs picanha bacon.  Spare ribs turkey ham tenderloin landjaeger kevin bacon cow fatback biltong shank meatloaf.  Pork loin chicken burgdoggen landjaeger cow tail shoulder kevin, meatloaf short loin.","Tail jowl pork belly pancetta doner meatball beef ribs ribeye fatback corned beef drumstick cow prosciutto ham short loin.  Meatball cupim pastrami, strip steak pork biltong shank burgdoggen.  Rump capicola ham doner landjaeger ground round.  Ham pastrami short ribs, ham hock salami jerky doner corned beef pancetta chicken turducken sirloin drumstick venison prosciutto.  Shankle bacon ham burgdoggen, tenderloin alcatra bresaola capicola venison beef ribs sirloin frankfurter meatball ground round.  Shoulder drumstick pastrami porchetta capicola pancetta.  Burgdoggen doner tongue, meatball alcatra ground round t-bone capicola pork loin chicken salami filet mignon short ribs tenderloin.  Turducken shoulder corned beef brisket cupim tongue bresaola tail bacon meatball boudin picanha capicola.","Kielbasa pork loin meatloaf ham hock, chuck flank ground round corned beef fatback doner landjaeger filet mignon ball tip tenderloin.  Tail corned beef venison shank.  Porchetta ham cupim pork frankfurter fatback shankle, boudin pork chop alcatra salami ribeye flank cow.  Pastrami ribeye tongue shank turducken hamburger.'
        ),
        array(
            'post_title' => 'Turducken jowl alcatra ham cow andouille beef ribs kevin',
            'post_excerpt' => 'Flank andouille t-bone biltong kielbasa leberkas.  Tongue chuck fatback alcatra, ball tip chicken ground round short loin shank t-bone beef brisket corned beef kielbasa doner.","Doner sirloin t-bone pork chop.  Capicola pork loin brisket prosciutto, pancetta tri-tip ribeye sirloin.  Beef ribs cupim boudin.',
            'post_content' => 'Chuck hamburger venison short ribs drumstick prosciutto bresaola boudin kevin.  Ball tip shoulder ground round pork loin sirloin, spare ribs tail pork chop leberkas strip steak pancetta frankfurter.  Andouille beef ribs pancetta strip steak leberkas swine.  Turkey bacon kevin picanha pork chop flank meatball ham.  Pastrami hamburger short loin shankle corned beef pork shoulder bresaola frankfurter jowl chicken capicola pork loin.  Short loin spare ribs filet mignon leberkas salami bacon.  Turkey leberkas kevin pancetta picanha short loin.","Shank swine shankle bresaola filet mignon drumstick leberkas short loin venison meatloaf burgdoggen kielbasa pork alcatra beef ribs.  Pork belly alcatra prosciutto, turducken capicola bacon beef ribs burgdoggen brisket andouille picanha pig cupim.  Pork loin sausage meatloaf shoulder.  Cow kevin andouille meatball chuck flank landjaeger porchetta rump tongue shankle filet mignon pancetta leberkas.  Andouille shank alcatra, tongue beef ribs bacon flank brisket kevin pork shankle chuck frankfurter sausage.  Pancetta meatloaf turkey, ribeye salami frankfurter tongue sirloin.  Jowl biltong pork chop cow spare ribs frankfurter, tongue pastrami boudin rump shankle.","Pastrami tongue turducken biltong hamburger jowl burgdoggen meatball ground round.  Shoulder pork belly landjaeger, doner cupim boudin shank filet mignon.  Boudin salami picanha pancetta pig shoulder beef fatback strip steak.  Chuck pancetta kevin, prosciutto andouille brisket cow doner.  Frankfurter cow spare ribs pork belly shankle.  Turducken jowl alcatra ham cow andouille beef ribs kevin frankfurter biltong.","Tongue swine bacon pork loin, alcatra tenderloin corned beef pork ribeye pork chop spare ribs pork picanha tenderloin chuck flank andouille t-bone biltong kielbasa leberkas.  Tongue chuck fatback alcatra, ball tip chicken ground round short loin shank t-bone beef brisket corned beef kielbasa doner.","Doner sirloin t-bone pork chop.  Capicola pork loin brisket prosciutto, pancetta tri-tip ribeye sirloin.  Beef ribs cupim boudin frankfurter tongue pastrami salami alcatra.  Swine picanha ground round, sirloin leberkas prosciutto shank rump tail doner corned beef burgdoggen.  Chuck strip steak chicken, swine turducken short loin leberkas venison ball tip prosciutto hamburger pig rump.  Doner rump shank bresaola biltong turducken.  Ribeye pancetta corned beef, boudin shankle pork loin venison pork belly.'
        ),
        array(
            'post_title' => 'Meatball cupim tenderloin spare ribs picanha jowl',
            'post_excerpt' => 'Pork cow leberkas biltong tongue chicken.  Landjaeger prosciutto ball tip frankfurter ground round bresaola turkey cow sausage hamburger leberkas jowl meatloaf brisket.  Beef boudin bresaola filet mignon ribeye beef ribs.  Hamburger meatloaf spare ribs, shank cow ham kielbasa shoulder pork.',
            'post_content' => 'Sirloin rump meatball bresaola drumstick leberkas pastrami andouille turducken kielbasa shoulder chuck frankfurter.  Turducken filet mignon shank salami beef.  Pork leberkas ball tip salami turkey kielbasa, boudin drumstick kevin jowl tail capicola swine andouille.  Alcatra swine pork belly, chuck jerky andouille shankle t-bone kevin.","Brisket beef ribs shank pancetta.  Spare ribs hamburger pork loin chuck, pork belly prosciutto cupim fatback ham hock strip steak cow flank bresaola porchetta.  Spare ribs rump meatloaf t-bone doner, strip steak frankfurter shoulder ham hock pork belly ground round beef bacon jerky.  Meatball sausage venison t-bone tenderloin.  Flank chuck ham, turkey jerky rump beef tail.  Alcatra drumstick sausage corned beef.","Pork cow leberkas biltong doner salami shankle prosciutto landjaeger porchetta.","Swine landjaeger meatloaf spare ribs sausage.  Porchetta cow ham hock ham, pork belly shank pork chop pork kielbasa ribeye pig cupim tongue.  Short ribs ground round porchetta turkey ham hock, salami landjaeger leberkas burgdoggen.  Pork belly burgdoggen shank leberkas.  Flank shank filet mignon, capicola ball tip meatloaf pork belly kielbasa burgdoggen.  Picanha tongue jowl landjaeger, boudin short loin andouille corned beef.  Pork belly fatback pork chop short ribs rump pancetta landjaeger jerky meatloaf cow strip steak sausage.'
        ),
        array(
            'post_title' => 'Tenderloin short ribs cow ground round, drumstick\'s kielbasa burgdoggen doner chicken',
            'post_excerpt' => 'Kielbasa jowl, ham hock beef ribs kevin prosciutto t-bone porchetta tail sausage.  Tri-tip sirloin frankfurter kielbasa, jerky spare ribs leberkas ham tenderloin.',
            'post_content' => 'Biltong strip steak shoulder, salami brisket turducken spare ribs.  T-bone meatball pork venison.  Prosciutto jowl andouille tri-tip brisket, pork salami tail burgdoggen pork chop ground round drumstick sausage pastrami beef ribs.  Rump pancetta chicken corned beef kevin.  Pork belly sirloin pork loin frankfurter leberkas.","Short loin ribeye cupim turducken, filet mignon sirloin picanha chuck kevin brisket.  Sirloin meatball corned beef kielbasa hamburger.  Shoulder ground round kevin, pork loin short ribs ham hock pancetta.  Ham hock cow kielbasa pork loin pig doner chuck pastrami.","Tenderloin pancetta leberkas short loin sirloin burgdoggen meatball frankfurter.  Capicola ball tip bresaola kielbasa jowl, ham hock beef ribs kevin prosciutto t-bone porchetta tail sausage.  Tenderloin short ribs cow ground round, drumstick kielbasa burgdoggen doner chicken t-bone turkey.  Ham hock frankfurter pork loin tongue porchetta ribeye tenderloin jowl fatback beef ribs tri-tip.  Pastrami meatball shankle pig drumstick.  Hamburger pancetta spare ribs tri-tip shankle pork tongue bresaola.","Boudin cupim rump, filet mignon turkey doner sausage tenderloin.  Strip steak swine meatball, prosciutto pig jerky flank.  Ribeye bacon boudin ham hock, turducken salami frankfurter pork loin pork chop jowl.  T-bone prosciutto burgdoggen short loin meatloaf beef chuck.'
        ),
        array(
            'post_title' => 'Ball tip, "pastrami sirloin" drumstick flank...',
            'post_excerpt' => 'Kevin meatball hamburger, cupim shank tenderloin frankfurter.  Landjaeger jowl venison kielbasa, bresaola tenderloin cupim brisket.  Boudin chuck corned beef jowl meatball.',
            'post_content' => 'Fatback capicola sirloin short loin.  Frankfurter pork chop shoulder chicken bresaola turkey.  Tongue sirloin flank, pancetta prosciutto landjaeger bresaola biltong shoulder ribeye short ribs sausage tri-tip brisket drumstick.  Spare ribs porchetta rump pastrami.","Turkey cupim bresaola ham hock biltong filet mignon picanha pork belly cow meatball.  Kevin fatback alcatra short loin flank short ribs doner meatloaf chuck bacon burgdoggen.  Chuck turkey turducken, beef ribs landjaeger biltong porchetta andouille brisket meatball short loin alcatra ham flank picanha.  Ball tip porchetta meatball sausage.  Swine porchetta fatback brisket.","Meatball picanha venison, brisket kielbasa prosciutto ball tip bresaola short ribs short loin porchetta ham hock filet mignon swine.  Pork chop turkey beef ribs shankle chicken shank meatball.  Sausage beef drumstick cow venison pork kielbasa cupim pig ribeye.  Landjaeger capicola ball tip, pastrami sirloin drumstick flank.","Flank chicken doner jowl.  Landjaeger doner pork chop venison.  Tail shank capicola pork belly venison, chicken kevin pork loin beef bresaola.  Pork burgdoggen frankfurter bacon drumstick rump cupim chicken.  Tenderloin pancetta doner meatball andouille burgdoggen turkey pork loin sirloin.  Chicken turkey burgdoggen venison.  Swine shoulder meatball short loin, pork jowl short ribs.'
        ),
        array(
            'post_title' => 'Chop short loin sausage tri-tip ribeye short ribs spare ribs meatloaf',
            'post_excerpt' => 'Shankle andouille picanha t-bone ground round chicken pastrami chuck.  Chicken alcatra pastrami tongue fatback brisket doner spare ribs porchetta capicola venison biltong flank sausage hamburger.',
            'post_content' => 'Beef ribs short loin shank pancetta, strip steak capicola cow beef pork rump spare ribs.  Pork chop frankfurter kevin pork loin meatball short loin filet mignon short ribs meatloaf kielbasa jowl sausage tail.  Frankfurter pastrami ball tip pancetta, swine short ribs hamburger ground round prosciutto turkey venison pig bacon jowl.  Meatloaf bacon cow, kielbasa pork loin beef ribs picanha ball tip tenderloin venison porchetta biltong.  Swine tongue landjaeger drumstick cupim, tri-tip pork chop.  Turkey chicken ham hock landjaeger t-bone, spare ribs kevin.","Shankle andouille picanha t-bone ground round chicken pastrami chuck.  Chicken alcatra pastrami tongue fatback brisket doner spare ribs porchetta capicola venison biltong flank sausage hamburger.  Doner kielbasa sausage frankfurter jerky, cupim pig salami alcatra shoulder.  Meatloaf cow doner chuck salami kielbasa filet mignon sirloin short ribs ball tip rump bacon.  Pork chop ball tip jerky chop shank hamburger cupim turducken bresaola.  Pork beef boudin, pork chop short loin sausage tri-tip ribeye short ribs spare ribs meatloaf.  Jerky hamburger turducken, tri-tip andouille tongue shoulder pork chop venison.","Burgdoggen jerky bacon beef, hamburger doner pork belly.  Andouille beef ribs porchetta, pastrami meatball bresaola jowl ham hock.  Bacon tail andouille ball tip bresaola pork loin pancetta venison turducken corned beef.  Andouille brisket pastrami landjaeger beef hamburger, fatback chicken swine turkey cow.  Salami kevin drumstick short loin, beef ribs corned beef tri-tip biltong boudin venison spare ribs t-bone cupim.  Drumstick ham shank ball tip.  Swine pork chop capicola strip steak, short ribs burgdoggen ham hock turkey sirloin.'
        ),
        array(
            'post_title' => 'Meatloaf turducken andouille jerky spare ribs filet mignon',
            'post_excerpt' => 'Shoulder salami ribeye shankle.  Jerky strip steak ham, cupim tail cow ball tip pig t-bone venison. Swine hamburger capicola, alcatra ribeye ham pancetta.  Meatloaf turducken andouille jerky spare ribs filet mignon cow pork loin pastrami beef tri-tip venison burgdoggen meatball.',
            'post_content' => 'Kielbasa swine ground round drumstick brisket filet mignon tenderloin alcatra.  Shankle capicola biltong filet mignon, short loin ribeye tail sausage turducken spare ribs pork chop ham hock rump short ribs drumstick.  Meatball boudin meatloaf andouille t-bone.  Shank beef salami prosciutto jerky jowl bresaola ham drumstick hamburger beef ribs shoulder.","Pastrami pork belly bacon pancetta hamburger swine hamburger capicola, alcatra ribeye ham pancetta.  Meatloaf turducken andouille jerky spare ribs filet mignon cow pork loin pastrami beef tri-tip venison burgdoggen meatball.  Biltong pastrami venison porchetta pork loin chuck.  Salami ball tip bresaola capicola leberkas, turducken chuck pastrami.  Filet mignon shoulder fatback short loin capicola drumstick bresaola.  Strip steak spare ribs burgdoggen salami cow, doner leberkas jerky corned beef alcatra.  Swine meatloaf turducken venison picanha pork chop turkey rump corned beef capicola strip steak drumstick biltong ground round shankle.","Tongue turkey short ribs jerky chuck shoulder turducken beef kevin.  Flank chuck capicola pork belly cupim.  Short loin meatloaf beef alcatra, jerky venison hamburger kielbasa kevin brisket frankfurter ground round.  Capicola burgdoggen spare ribs, shank tri-tip meatloaf porchetta chuck.'
        ),
        array(
            'post_title' => 'Bresaola leberkas picanha pork belly capicola...',
            'post_excerpt' => 'Bresaola biltong brisket doner.  Sirloin prosciutto burgdoggen, shankle pork belly cow capicola pork chop ham hock pancetta doner ball tip.  T-bone boudin shank capicola doner, tongue',
            'post_content' => 'Short ribs tri-tip corned beef hamburger tongue frankfurter meatloaf flank t-bone pork turkey leberkas biltong salami.  Bacon cupim fatback, capicola ham pancetta pig ham hock.  Biltong landjaeger jowl short loin t-bone.  Short ribs hamburger alcatra turducken.  Fatback pork loin sirloin, turducken corned beef beef burgdoggen bresaola salami frankfurter pork chop andouille shoulder boudin cupim.  Chuck pig cupim capicola chicken t-bone kevin filet mignon boudin bacon andouille pancetta pork loin leberkas.","Picanha beef ribs shankle short ribs sirloin pork hamburger ground round.  Bresaola leberkas picanha pork belly capicola.  Salami brisket sirloin capicola, beef rump turducken leberkas.  Corned beef t-bone tri-tip capicola tail ball tip.  Prosciutto andouille ham brisket biltong leberkas, kielbasa capicola picanha hamburger meatloaf salami.  Pig capicola doner, pastrami flank beef ribs prosciutto andouille chicken drumstick picanha chuck pork meatball T-bone boudin shank capicola doner, tongue drumstick chuck frankfurter short ribs cow pig.  Short loin tail fatback porchetta ham short ribs kielbasa spare ribs tenderloin meatball ground round.","Biltong short ribs beef ribs landjaeger strip steak bresaola, pig porchetta brisket pork chop tongue shankle sirloin venison.  Cupim venison shoulder swine chuck.  Brisket pork belly sausage prosciutto turkey biltong shoulder kielbasa doner.  Venison tongue salami corned beef, chicken capicola pancetta shankle leberkas pork loin.","Short ribs turkey tongue capicola, sausage brisket andouille pastrami boudin bresaola doner corned beef.  Short ribs ground round ribeye bresaola brisket.  Strip steak chicken kevin t-bone jerky ground round sirloin.  Kielbasa tail pastrami, tri-tip burgdoggen ham hock short ribs cow ball tip porchetta doner pork chop drumstick.  Sausage biltong ribeye andouille spare ribs.  Boudin capicola ball tip swine venison drumstick meatball picanha pork loin flank beef ribs.'
        ),
        array(
            'post_title' => 'Kevin beef hamburger pastrami cow shankle filet mignon landjaeger corned beef ball tip drumstick',
            'post_excerpt' => 'Venison rump jerky beef ribs salami cow.  Andouille jowl t-bone shankle prosciutto.  Shoulder bacon pancetta, short ribs t-bone pastrami cow short loin beef',
            'post_content' => 'Flank sausage turkey ribeye.  Venison rump jerky beef ribs salami cow.  Andouille jowl t-bone shankle prosciutto.  Shoulder bacon pancetta, short ribs t-bone pastrami cow short loin beef ribs spare ribs tenderloin pork cupim doner pork chop.  Alcatra drumstick jowl brisket kevin shankle ball tip short ribs pastrami rump pork prosciutto t-bone.  Corned beef meatball brisket sirloin pancetta.  Ground round porchetta sausage, shoulder kevin tenderloin sirloin shank meatloaf ham tail.","Strip steak ball tip jowl landjaeger, sirloin cupim pork belly ground round corned beef porchetta.  Shankle ham hock t-bone ball tip, jowl venison fatback.  Short loin pancetta swine picanha.  Pastrami frankfurter biltong, corned beef chicken ball tip turducken pork kielbasa.  Jowl turkey boudin ham hock.  Burgdoggen boudin beef ribs kevin jowl kielbasa chuck shank.  Biltong corned beef strip steak turkey.","Beef shoulder drumstick, kevin turducken pastrami spare ribs strip steak flank capicola andouille boudin short loin brisket.  Pork chop short ribs drumstick biltong, tenderloin kevin jowl sausage.  Brisket spare ribs shankle ground round bresaola.  Meatball filet mignon kevin venison spare ribs bacon doner pork corned beef alcatra andouille picanha.  Swine short loin pork belly cow ball tip venison burgdoggen, kevin turducken ham pork. Beef ball tip drumstick.  Kielbasa pastrami fatback, drumstick short loin biltong doner chuck leberkas pork chop swine hamburger.  Picanha shankle hamburger rump fatback porchetta bresaola turkey meatball beef ribs ground round alcatra doner strip steak.  Bresaola tongue pork loin sirloin, shank frankfurter chuck filet mignon chicken beef t-bone boudin hamburger.'
        )
    );

    // Get rand content
    $rand_key = array_rand( $array, 1 );
    $return = ( isset($array[$rand_key][$key]) ) ? sanitize_text_field( $array[$rand_key][$key] ) : '' ;

    return $return;
}